# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold

# Import the Dataset

Link:"https://raw.githubusercontent.com/omairaasim/machine_learning/master/project_11_k_nearest_neighbor/iphone_purchase_records.csv"

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/omairaasim/machine_learning/master/project_11_k_nearest_neighbor/iphone_purchase_records.csv")

In [3]:
df.head()

   Gender  Age  Salary  Purchase Iphone
0    Male   19   19000                0
1    Male   35   20000                0
2  Female   26   43000                0
3  Female   27   57000                0
4    Male   19   76000                0

In [4]:
df.shape

(400, 4)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           400 non-null    object
 1   Age              400 non-null    int64
 2   Salary           400 non-null    int64
 3   Purchase Iphone  400 non-null    int64
dtypes: int64(3), object(1)
memory usage: 12.6+ KB

# Spliting of Data

In [6]:
df.head(10)

   Gender  Age  Salary  Purchase Iphone
0    Male   19   19000                0
1    Male   35   20000                0
2  Female   26   43000                0
3  Female   27   57000                0
4    Male   19   76000                0
5    Male   27   58000                0
6  Female   27   84000                0
7  Female   32  150000                1
8    Male   25   33000                0
9  Female   35   65000                0

In [7]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [8]:
x

     Gender  Age  Salary
0      Male   19   19000
1      Male   35   20000
2    Female   26   43000
3    Female   27   57000
4      Male   19   76000
..      ...  ...     ...
395  Female   46   41000
396    Male   51   23000
397  Female   50   20000
398    Male   36   33000
399  Female   49   36000

[400 rows x 3 columns]

In [9]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchase Iphone, Length: 400, dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
enc=LabelEncoder()

In [12]:
x.Gender = enc.fit_transform(x.Gender)

In [13]:
x

     Gender  Age  Salary
0         1   19   19000
1         1   35   20000
2         0   26   43000
3         0   27   57000
4         1   19   76000
..      ...  ...     ...
395       0   46   41000
396       1   51   23000
397       0   50   20000
398       1   36   33000
399       0   49   36000

[400 rows x 3 columns]

In [14]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Gender  400 non-null    int32
 1   Age     400 non-null    int64
 2   Salary  400 non-null    int64
dtypes: int32(1), int64(2)
memory usage: 7.9 KB

# Splitting the data into sets

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

# Feature Scaling

In [16]:
scale =  StandardScaler()

In [17]:
x_train= scale.fit_transform(x_train)
x_test= scale.fit_transform(x_test)

In [18]:
x_train

array([[-9.92882472e-01, -9.79100420e-01, -1.11059025e+00],
       [-9.92882472e-01, -2.03575335e-01,  5.66967998e-02],
       [ 1.00716855e+00,  1.15359356e+00, -1.19813678e+00],
       [ 1.00716855e+00, -2.03575335e-01,  6.40340327e-01],
       [ 1.00716855e+00, -9.69406357e-03,  1.73425505e-01],
       [-9.92882472e-01, -4.94397242e-01,  1.39907691e+00],
       [-9.92882472e-01, -1.06634699e-01,  1.73425505e-01],
       [ 1.00716855e+00, -1.65768487e+00,  4.94429445e-01],
       [-9.92882472e-01,  8.72465721e-02, -5.56128904e-01],
       [-9.92882472e-01,  1.15359356e+00, -9.64679373e-01],
       [ 1.00716855e+00,  2.81127843e-01, -1.18396258e-01],
       [ 1.00716855e+00, -9.69406357e-03,  2.31789858e-01],
       [-9.92882472e-01,  2.21994056e+00, -6.72857609e-01],
       [-9.92882472e-01,  1.05665293e+00,  2.01190262e+00],
       [ 1.00716855e+00,  2.81127843e-01,  5.66967998e-02],
       [-9.92882472e-01, -1.06634699e-01, -1.76760611e-01],
       [ 1.00716855e+00, -1.07604106e+00,  3.48518563e-01],
       [ 1.00716855e+00, -3.97456606e-01, -1.11059025e+00],
       [-9.92882472e-01,  3.78068479e-01, -5.26946727e-01],
       [-9.92882472e-01,  8.62771657e-01,  1.44243329e-01],
       [ 1.00716855e+00, -1.85156614e+00,  3.77700740e-01],
       [-9.92882472e-01, -9.69406357e-03, -1.05222590e+00],
       [ 1.00716855e+00, -2.03575335e-01, -4.68582375e-01],
       [-9.92882472e-01, -8.82159785e-01, -2.93489316e-01],
       [-9.92882472e-01, -9.69406357e-03,  5.66967998e-02],
       [-9.92882472e-01, -1.85156614e+00, -7.31221962e-01],
       [ 1.00716855e+00,  8.72465721e-02, -2.35124964e-01],
       [-9.92882472e-01, -2.03575335e-01, -1.18396258e-01],
       [ 1.00716855e+00, -5.91337878e-01, -8.92140820e-02],
       [ 1.00716855e+00,  9.59712293e-01, -1.28568331e+00],
       [ 1.00716855e+00,  4.75009115e-01,  1.01970862e+00],
       [ 1.00716855e+00, -1.75462551e+00, -1.46077637e+00],
       [ 1.00716855e+00, -1.56074423e+00,  8.58789761e-02],
       [ 1.00716855e+00, -8.82159785e-01, -1.08140808e+00],
       [ 1.00716855e+00,  1.44441547e+00,  2.36208873e+00],
       [-9.92882472e-01,  1.54135611e+00,  1.01970862e+00],
       [ 1.00716855e+00, -1.17298169e+00,  3.19336387e-01],
       [-9.92882472e-01, -1.07604106e+00,  8.58789761e-02],
       [-9.92882472e-01, -1.07604106e+00, -1.57750508e+00],
       [-9.92882472e-01,  2.81127843e-01,  2.12863132e+00],
       [ 1.00716855e+00, -2.03575335e-01, -9.06315020e-01],
       [-9.92882472e-01,  1.92911865e+00,  1.54498779e+00],
       [ 1.00716855e+00,  3.78068479e-01,  5.23611621e-01],
       [-9.92882472e-01, -1.26992233e+00,  5.81975974e-01],
       [ 1.00716855e+00, -9.69406357e-03, -4.97764551e-01],
       [ 1.00716855e+00, -2.03575335e-01,  1.13643732e+00],
       [ 1.00716855e+00, -4.94397242e-01,  9.02979914e-01],
       [-9.92882472e-01, -2.03575335e-01,  2.27454220e+00],
       [-9.92882472e-01, -1.75462551e+00, -1.25650114e+00],
       [-9.92882472e-01,  8.62771657e-01,  3.77700740e-01],
       [ 1.00716855e+00,  9.59712293e-01,  1.04889080e+00],
       [-9.92882472e-01,  7.65831022e-01, -7.02039785e-01],
       [ 1.00716855e+00,  8.72465721e-02, -5.26946727e-01],
       [-9.92882472e-01, -9.69406357e-03,  6.98704680e-01],
       [ 1.00716855e+00, -7.85219149e-01, -7.60404138e-01],
       [-9.92882472e-01,  3.78068479e-01, -1.13977243e+00],
       [-9.92882472e-01,  2.81127843e-01, -2.64307140e-01],
       [ 1.00716855e+00, -9.79100420e-01,  5.52793798e-01],
       [ 1.00716855e+00, -9.79100420e-01,  6.11158150e-01],
       [-9.92882472e-01,  1.84187208e-01,  5.66967998e-02],
       [-9.92882472e-01, -1.36686296e+00, -1.19813678e+00],
       [-9.92882472e-01,  1.34747484e+00,  2.24536003e+00],
       [ 1.00716855e+00, -1.36686296e+00, -1.76760611e-01],
       [-9.92882472e-01, -9.69406357e-03,  3.19336387e-01],
       [ 1.00716855e+00,  2.81127843e-01, -6.43675433e-01],
       [-9.92882472e-01,  1.05665293e+00, -1.16895461e+00],
       [ 1.00716855e+00, -2.03575335e-01, -2.93489316e-01],
       [ 1.00716855e+00, -1.07604106e+00, -1.13977243e+00],
       [ 1.00716855e+00,  1.84187208e-01,  1.07807297e+00],
       [-9.92882472e-01, -8.82159785e-01,  4.36065092e-01],
       [-9.92882472e-01,  2.12299992e+00,  2.02607682e-01],
       [ 1.00716855e+00,  2.81127843e-01, -3.51853669e-01],
       [-9.92882472e-01, -2.03575335e-01,  8.15433385e-01],
       [ 1.00716855e+00, -1.07604106e+00,  4.94429445e-01],
       [-9.92882472e-01,  3.78068479e-01, -1.76760611e-01],
       [-9.92882472e-01, -7.85219149e-01, -6.43675433e-01],
       [-9.92882472e-01, -1.07604106e+00, -1.51914072e+00],
       [-9.92882472e-01,  2.02605929e+00, -1.34404767e+00],
       [-9.92882472e-01, -6.88278513e-01, -2.05942787e-01],
       [ 1.00716855e+00, -1.17298169e+00, -1.05222590e+00],
       [-9.92882472e-01,  2.12299992e+00, -1.16895461e+00],
       [-9.92882472e-01, -8.82159785e-01, -9.35497196e-01],
       [ 1.00716855e+00,  1.84187208e-01,  2.31789858e-01],
       [-9.92882472e-01,  9.59712293e-01,  1.10725515e+00],
       [-9.92882472e-01,  1.44441547e+00,  2.01190262e+00],
       [ 1.00716855e+00, -7.85219149e-01, -7.60404138e-01],
       [-9.92882472e-01, -9.79100420e-01,  1.98272044e+00],
       [-9.92882472e-01, -1.26992233e+00, -4.10218022e-01],
       [-9.92882472e-01,  2.81127843e-01,  8.58789761e-02],
       [-9.92882472e-01, -1.56074423e+00, -1.54832290e+00],
       [-9.92882472e-01,  1.92911865e+00, -1.25650114e+00],
       [ 1.00716855e+00, -6.88278513e-01,  1.92435609e+00],
       [-9.92882472e-01,  1.05665293e+00,  1.45744126e+00],
       [ 1.00716855e+00,  2.81127843e-01, -3.51853669e-01],
       [ 1.00716855e+00, -2.03575335e-01,  1.73425505e-01],
       [-9.92882472e-01, -8.82159785e-01, -7.31221962e-01],
       [ 1.00716855e+00, -9.69406357e-03,  1.44243329e-01],
       [ 1.00716855e+00, -2.03575335e-01, -1.22731896e+00],
       [ 1.00716855e+00, -9.69406357e-03,  2.90154211e-01],
       [ 1.00716855e+00, -4.94397242e-01,  1.48662344e+00],
       [ 1.00716855e+00, -7.85219149e-01,  1.73425505e-01],
       [ 1.00716855e+00, -6.88278513e-01, -1.51914072e+00],
       [ 1.00716855e+00, -1.17298169e+00,  2.90154211e-01],
       [ 1.00716855e+00,  2.81127843e-01,  1.10725515e+00],
       [ 1.00716855e+00, -1.26992233e+00, -1.46077637e+00],
       [-9.92882472e-01,  3.78068479e-01,  8.58789761e-02],
       [ 1.00716855e+00,  8.72465721e-02, -2.35124964e-01],
       [ 1.00716855e+00, -1.06634699e-01,  2.18699567e+00],
       [ 1.00716855e+00,  4.75009115e-01, -1.47578435e-01],
       [ 1.00716855e+00,  1.05665293e+00, -1.05222590e+00],
       [-9.92882472e-01,  1.05665293e+00, -1.13977243e+00],
       [ 1.00716855e+00, -1.36686296e+00, -1.43159419e+00],
       [-9.92882472e-01,  1.73523738e+00,  1.77844520e+00],
       [ 1.00716855e+00, -7.85219149e-01,  2.30372438e+00],
       [ 1.00716855e+00,  4.75009115e-01, -1.18396258e-01],
       [-9.92882472e-01, -9.79100420e-01, -4.39400198e-01],
       [ 1.00716855e+00, -9.69406357e-03, -4.10218022e-01],
       [ 1.00716855e+00, -1.17298169e+00, -1.37322984e+00],
       [ 1.00716855e+00,  2.12299992e+00,  2.15781350e+00],
       [ 1.00716855e+00,  4.75009115e-01, -4.39400198e-01],
       [-9.92882472e-01, -9.79100420e-01, -1.51914072e+00],
       [-9.92882472e-01,  9.59712293e-01, -5.85311080e-01],
       [ 1.00716855e+00, -8.82159785e-01, -2.93489316e-01],
       [-9.92882472e-01, -3.97456606e-01, -1.66755293e-03],
       [-9.92882472e-01, -5.91337878e-01, -3.08497293e-02],
       [-9.92882472e-01, -2.03575335e-01, -1.34404767e+00],
       [ 1.00716855e+00, -2.03575335e-01, -1.37322984e+00],
       [-9.92882472e-01,  1.92911865e+00, -1.05222590e+00],
       [ 1.00716855e+00, -6.88278513e-01,  1.10725515e+00],
       [ 1.00716855e+00,  8.62771657e-01, -1.34404767e+00],
       [-9.92882472e-01,  3.78068479e-01, -2.64307140e-01],
       [-9.92882472e-01, -3.97456606e-01, -8.18768491e-01],
       [-9.92882472e-01, -3.97456606e-01, -2.64307140e-01],
       [-9.92882472e-01,  9.59712293e-01, -6.43675433e-01],
       [-9.92882472e-01, -8.82159785e-01, -4.10218022e-01],
       [ 1.00716855e+00,  7.65831022e-01, -1.08140808e+00],
       [ 1.00716855e+00, -2.03575335e-01,  1.73425505e-01],
       [-9.92882472e-01,  2.12299992e+00, -7.89586314e-01],
       [-9.92882472e-01,  9.59712293e-01, -5.56128904e-01],
       [-9.92882472e-01,  9.59712293e-01, -5.26946727e-01],
       [ 1.00716855e+00, -2.03575335e-01,  2.90154211e-01],
       [ 1.00716855e+00,  1.84187208e-01, -7.89586314e-01],
       [ 1.00716855e+00,  2.81127843e-01,  2.60972034e-01],
       [-9.92882472e-01, -1.36686296e+00, -6.14493256e-01],
       [-9.92882472e-01,  1.84187208e-01,  1.73425505e-01],
       [-9.92882472e-01, -2.03575335e-01, -3.51853669e-01],
       [ 1.00716855e+00,  1.73523738e+00, -8.77132844e-01],
       [-9.92882472e-01, -5.91337878e-01,  5.66967998e-02],
       [ 1.00716855e+00, -8.82159785e-01,  1.57416997e+00],
       [ 1.00716855e+00,  4.75009115e-01,  3.19336387e-01],
       [ 1.00716855e+00,  2.81127843e-01, -2.93489316e-01],
       [ 1.00716855e+00,  1.05665293e+00,  1.44243329e-01],
       [ 1.00716855e+00, -1.56074423e+00,  5.52793798e-01],
       [ 1.00716855e+00,  1.54135611e+00,  8.58789761e-02],
       [-9.92882472e-01, -9.79100420e-01, -3.22671493e-01],
       [-9.92882472e-01, -2.03575335e-01, -6.43675433e-01],
       [ 1.00716855e+00, -8.82159785e-01,  5.81975974e-01],
       [ 1.00716855e+00, -1.07604106e+00,  3.19336387e-01],
       [-9.92882472e-01, -4.94397242e-01,  1.39907691e+00],
       [-9.92882472e-01,  4.75009115e-01,  1.73425505e-01],
       [-9.92882472e-01, -3.97456606e-01,  2.33290656e+00],
       [-9.92882472e-01,  3.78068479e-01,  3.19336387e-01],
       [ 1.00716855e+00, -5.91337878e-01, -3.22671493e-01],
       [ 1.00716855e+00,  1.84187208e-01,  1.89517391e+00],
       [ 1.00716855e+00, -9.79100420e-01, -1.43159419e+00],
       [-9.92882472e-01, -7.85219149e-01,  4.06882916e-01],
       [ 1.00716855e+00, -1.75462551e+00,  2.75146234e-02],
       [ 1.00716855e+00, -1.75462551e+00,  4.65247269e-01],
       [ 1.00716855e+00, -7.85219149e-01, -2.35124964e-01],
       [-9.92882472e-01,  1.84187208e-01,  1.89517391e+00],
       [ 1.00716855e+00, -5.91337878e-01,  2.02607682e-01],
       [ 1.00716855e+00,  3.78068479e-01,  8.58789761e-02],
       [-9.92882472e-01, -1.07604106e+00,  3.19336387e-01],
       [ 1.00716855e+00,  2.81127843e-01, -2.35124964e-01],
       [-9.92882472e-01, -2.03575335e-01, -1.28568331e+00],
       [-9.92882472e-01,  1.05665293e+00,  7.86251209e-01],
       [ 1.00716855e+00,  4.75009115e-01,  2.33290656e+00],
       [ 1.00716855e+00, -8.82159785e-01,  2.90154211e-01],
       [-9.92882472e-01,  1.34747484e+00,  1.89517391e+00],
       [-9.92882472e-01, -3.97456606e-01, -1.19813678e+00],
       [ 1.00716855e+00,  4.75009115e-01, -4.39400198e-01],
       [ 1.00716855e+00,  7.65831022e-01, -1.37322984e+00],
       [-9.92882472e-01, -9.69406357e-03, -3.51853669e-01],
       [ 1.00716855e+00, -3.00515971e-01,  1.25316603e+00],
       [ 1.00716855e+00, -2.03575335e-01, -8.77132844e-01],
       [-9.92882472e-01, -1.46380360e+00, -1.22731896e+00],
       [-9.92882472e-01, -2.03575335e-01,  8.58789761e-02],
       [-9.92882472e-01,  1.84187208e-01, -2.93489316e-01],
       [ 1.00716855e+00, -1.65768487e+00,  1.44243329e-01],
       [-9.92882472e-01,  8.62771657e-01, -1.08140808e+00],
       [-9.92882472e-01, -1.07604106e+00, -7.60404138e-01],
       [-9.92882472e-01, -7.85219149e-01,  4.06882916e-01],
       [-9.92882472e-01,  1.73523738e+00,  1.63253432e+00],
       [-9.92882472e-01, -9.69406357e-03,  2.24536003e+00],
       [-9.92882472e-01,  7.65831022e-01,  1.80762738e+00],
       [ 1.00716855e+00, -3.97456606e-01, -7.60404138e-01],
       [ 1.00716855e+00,  3.78068479e-01, -7.02039785e-01],
       [-9.92882472e-01,  4.75009115e-01,  2.90154211e-01],
       [-9.92882472e-01, -9.69406357e-03,  1.98272044e+00],
       [ 1.00716855e+00, -1.26992233e+00,  4.36065092e-01],
       [ 1.00716855e+00, -4.94397242e-01, -1.48995855e+00],
       [-9.92882472e-01,  1.83217801e+00,  1.01970862e+00],
       [-9.92882472e-01,  1.15359356e+00, -8.77132844e-01],
       [-9.92882472e-01, -8.82159785e-01,  4.65247269e-01],
       [-9.92882472e-01,  1.54135611e+00,  2.15781350e+00],
       [ 1.00716855e+00, -6.88278513e-01,  5.81975974e-01],
       [ 1.00716855e+00,  1.92911865e+00, -2.64307140e-01],
       [ 1.00716855e+00,  2.81127843e-01,  1.73425505e-01],
       [ 1.00716855e+00,  3.78068479e-01,  2.90154211e-01],
       [-9.92882472e-01, -1.65768487e+00,  3.77700740e-01],
       [-9.92882472e-01, -1.46380360e+00, -4.10218022e-01],
       [ 1.00716855e+00, -2.03575335e-01,  5.52793798e-01],
       [ 1.00716855e+00,  1.63829674e+00,  2.75146234e-02],
       [-9.92882472e-01, -5.91337878e-01, -1.57750508e+00],
       [-9.92882472e-01,  1.25053420e+00, -9.64679373e-01],
       [ 1.00716855e+00,  4.75009115e-01, -1.18396258e-01],
       [ 1.00716855e+00, -3.00515971e-01, -7.60404138e-01],
       [-9.92882472e-01,  4.75009115e-01,  1.13643732e+00],
       [-9.92882472e-01,  1.63829674e+00, -1.25650114e+00],
       [-9.92882472e-01, -1.75462551e+00, -1.40241202e+00],
       [-9.92882472e-01, -1.06634699e-01, -5.56128904e-01],
       [ 1.00716855e+00, -9.69406357e-03,  2.75146234e-02],
       [-9.92882472e-01, -1.06634699e-01,  1.66171650e+00],
       [ 1.00716855e+00,  9.59712293e-01, -1.43159419e+00],
       [-9.92882472e-01, -6.88278513e-01,  2.90154211e-01],
       [-9.92882472e-01,  2.12299992e+00,  4.06882916e-01],
       [ 1.00716855e+00, -7.85219149e-01,  3.19336387e-01],
       [-9.92882472e-01,  5.71949750e-01,  1.25316603e+00],
       [-9.92882472e-01,  8.72465721e-02,  3.19336387e-01],
       [ 1.00716855e+00,  2.02605929e+00,  2.18699567e+00],
       [ 1.00716855e+00, -1.06634699e-01,  1.63253432e+00],
       [ 1.00716855e+00,  1.15359356e+00, -1.19813678e+00],
       [ 1.00716855e+00, -1.85156614e+00, -4.97764551e-01],
       [ 1.00716855e+00, -6.88278513e-01, -1.57750508e+00],
       [-9.92882472e-01,  2.12299992e+00,  5.52793798e-01],
       [-9.92882472e-01, -9.79100420e-01, -3.51853669e-01],
       [ 1.00716855e+00,  8.72465721e-02,  5.66967998e-02],
       [-9.92882472e-01, -5.91337878e-01,  5.81975974e-01],
       [ 1.00716855e+00,  9.59712293e-01, -1.02304373e+00],
       [ 1.00716855e+00, -5.91337878e-01,  1.44243329e-01],
       [ 1.00716855e+00, -9.69406357e-03,  8.58789761e-02],
       [ 1.00716855e+00,  2.81127843e-01, -3.51853669e-01],
       [ 1.00716855e+00,  2.12299992e+00,  1.77844520e+00],
       [ 1.00716855e+00,  1.15359356e+00, -1.18396258e-01],
       [ 1.00716855e+00,  1.05665293e+00,  6.11158150e-01],
       [-9.92882472e-01,  8.62771657e-01, -1.37322984e+00],
       [-9.92882472e-01,  1.63829674e+00,  1.01970862e+00],
       [ 1.00716855e+00, -2.03575335e-01, -1.43159419e+00],
       [-9.92882472e-01,  1.15359356e+00,  2.09944914e+00],
       [ 1.00716855e+00,  1.05665293e+00, -8.18768491e-01],
       [ 1.00716855e+00, -2.03575335e-01, -4.10218022e-01],
       [ 1.00716855e+00, -1.06634699e-01, -2.64307140e-01],
       [-9.92882472e-01, -4.94397242e-01,  2.36208873e+00],
       [-9.92882472e-01, -1.85156614e+00, -3.08497293e-02],
       [ 1.00716855e+00, -1.26992233e+00, -4.10218022e-01],
       [-9.92882472e-01,  4.75009115e-01,  6.11158150e-01],
       [ 1.00716855e+00,  8.72465721e-02, -2.93489316e-01],
       [-9.92882472e-01,  2.21994056e+00,  1.13643732e+00],
       [-9.92882472e-01, -1.46380360e+00, -1.76760611e-01],
       [-9.92882472e-01, -1.26992233e+00, -1.08140808e+00],
       [ 1.00716855e+00,  8.62771657e-01, -2.93489316e-01],
       [-9.92882472e-01,  1.05665293e+00,  1.89517391e+00],
       [-9.92882472e-01,  3.78068479e-01,  8.58789761e-02],
       [-9.92882472e-01,  1.25053420e+00, -7.31221962e-01],
       [ 1.00716855e+00,  8.72465721e-02,  5.66967998e-02],
       [ 1.00716855e+00, -1.26992233e+00, -1.34404767e+00],
       [ 1.00716855e+00, -2.03575335e-01, -2.35124964e-01],
       [-9.92882472e-01, -9.69406357e-03,  3.19336387e-01],
       [-9.92882472e-01, -1.26992233e+00, -1.22731896e+00],
       [-9.92882472e-01, -1.07604106e+00,  4.36065092e-01],
       [-9.92882472e-01, -3.00515971e-01, -1.28568331e+00],
       [-9.92882472e-01, -1.06634699e-01, -4.39400198e-01],
       [-9.92882472e-01, -1.56074423e+00, -3.08497293e-02],
       [-9.92882472e-01,  3.78068479e-01,  5.66967998e-02],
       [ 1.00716855e+00,  2.21994056e+00, -7.89586314e-01],
       [-9.92882472e-01,  1.44441547e+00,  6.11158150e-01],
       [-9.92882472e-01, -1.65768487e+00, -1.34404767e+00],
       [ 1.00716855e+00,  1.34747484e+00, -1.34404767e+00],
       [ 1.00716855e+00,  8.62771657e-01,  2.90154211e-01],
       [ 1.00716855e+00, -6.88278513e-01, -5.85311080e-01]])

# Model Selection

In [19]:
log = LogisticRegression()
knn = KNeighborsClassifier(n_neighbors=5)

# Fitting the model

In [20]:
log.fit(x_train,y_train)
knn.fit(x_train,y_train)

KNeighborsClassifier()

# Test the model

In [29]:
y_knn_pred = knn.predict(x_test)

In [32]:
from sklearn.metrics import accuracy_score

In [33]:
accuracy_score(y_test,y_knn_pred)

0.6666666666666666

In [34]:
lis=[i for i in range(1,9)]

In [35]:
acc=[]
dic={}
for i in lis:
    knn=KNeighborsClassifier(n_neighbors=i)
    knn.fit(x_train,y_train)
    y_knn_pred= knn.predict(x_test)
    acc.append(accuracy_score(y_test,y_knn_pred))
#     dic[i]=accuracy_score(y_test,y_knn_pred)
    
print(max(acc))

0.8916666666666667

In [87]:
y_log_pred=log.predict(x_test)

In [88]:
accuracy_score(y_test,y_log_pred)

0.725

In [6]:
%autosave 20

Autosaving every 20 seconds